name: ptys_551
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - rasterio
  - numpy
  - matplotlib
  - scipy
  - tqdm
  - scikit-learn
  - spectral
  - ipython
  - pandas
  - glob2
  - pip:
      - PyQt5
      - outliers
