name: ptys_551
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.10
  - ipykernel
  - rasterio
  - matplotlib
  - scipy
  - tqdm
  - scikit-learn
  - spectral
  - ipython
  - pandas
  - glob2
  - pip
  - pip:
      - PyQt5
      - outlier-utils
      - numpy==1.23.0
